### ISSUE TITLE
2 letter word can not be italic

### ISSUE THREAD

**Issue by hbrls** [Lukasa/language-restructuredtext#11]
![screen shot](https://cloud.githubusercontent.com/assets/1220476/6983635/c3e6d652-da52-11e4-99bd-1f830e826cdb.png)

3 and more letters are fine. Chinese characters meet the same issue.

2 letter bold is fine.

**Comment by Lukasa** [comment]
It looks like, for no adequately explainable reason, the grammar is slightly different for bold and italic.

Bold:

```cson
'match': '(\\*\\*)[^*]+(\\*\\*)'
```

Italic:

```cson
'match': '(\\*)\\w[^*]+\\w(\\*)'
```

It is hard to see why the italics regex is not: `'(\\*)[^*]+(\\*)'`.

**Comment by Lukasa** [comment]
If I make that change the italics problem does appear to be fixed.

**Comment by Lukasa** [comment]
@hbrls Care to test the branch in #12 for me, and confirm that it both fixes the problem and doesn't unexpectedly break any of the rest of your rendering?

**Comment by hbrls** [comment]
@Lukasa Was the behavior correct in TextMate?

ps, I'll  be able to test that after the holiday. I'm still having other issues, maybe I'll make a test case for human eyes first.

**Comment by Lukasa** [comment]
I suspect the answer is no, but I never used TextMate so I'm frankly unsure.
