### ISSUE TITLE
Directives with domains names are not parsed correctly

### ISSUE THREAD

**Issue by Luthaf** [Lukasa/language-restructuredtext#13]
Directives with domains like theses: 
```
.. py:functions:: foo(bar) 

.. cpp:class:: Name
```
are parsed and highlighted as comments.

The same issue seems to appears with the Github highlighting:
```rest
.. code::

.. py:class:: Test
```

**Comment by Alhadis** [comment]
@Luthaf This is easily fixed. =) Could you tell me more about these directives, and what they're supposed to look like?

(I've only recently gotten into reStructuredText, so I'm still learning about the language. Loving it a whole lot more than Markdown)

**Comment by Luthaf** [comment]
These are directives for documenting functions/classes/... inside a specific [sphinx domain](http://www.sphinx-doc.org/en/stable/domains.html) (Python, C++, ...). They should look like other directives, like the `.. code::` one.

**Comment by Alhadis** [comment]
I'll work on it right now. =) Merci!

(I speak French better than Python, it would seem...)

**Comment by Alhadis** [comment]
... okay, this might take a while. This entire grammar needs to be, uhm, restructured.

**Comment by Luthaf** [comment]
\o/ Thanks!
