### ISSUE TITLE
Failure when using * to start a bullet list and * or ** again to set italic/bold text

### ISSUE THREAD

**Issue by Yajo** [Lukasa/language-restructuredtext#17]
I think this screenshot will show you what I mean:

![captura de pantalla de 2015-05-18 12 46 09](https://cloud.githubusercontent.com/assets/973709/7679327/e91cade4-fd5b-11e4-9b3b-ba4f29f8835a.png)

As you can see, the \* for the bullet list is confused with those of text formatting.

**Comment by Lukasa** [comment]
Good spot.

Right now this grammar doesn't actually do *anything* for bulleted lists in the grammar. I'm not instantly sure how to resolve this, I'll have a think.

**Comment by Lukasa** [comment]
So right now I'm getting the impression that this is one of those issues that's tricky to solve with regular expressions, and they're a good example of how many markup formats are not regular languages.

Given the inferiority of regular expressions in this instance, I'm going to do the best I can, and forbid that the character immediately after a `*` be whitespace. Ideally I'd have some other logic around matching a list, but that's a *massive* pain.

**Comment by Lukasa** [comment]
Resolved in 0.6.0. Thanks for the report! :cake: :sparkles:

**Comment by Yajo** [comment]
It does the trick. Sometimes the simplest solution is the right one ;)
