### ISSUE TITLE
Footer links with / are taken as comment start

### ISSUE THREAD

**Issue by Yajo** [Lukasa/language-restructuredtext#18]
The `/` character in `yajo/sass` causes the following highlight:

![captura de pantalla de 2015-07-15 13-06-05](https://cloud.githubusercontent.com/assets/973709/8697099/8fb7c620-2af2-11e5-8404-9bf8f1689172.png)

**Comment by Lukasa** [comment]
Thanks for the report! I believe I've fixed this problem in the 0.7.0 release: please update and confirm the fix. =)

**Comment by Yajo** [comment]
Fixed.

**Comment by Lukasa** [comment]
\o/ Thanks for the report @Yajo!

**Comment by Yajo** [comment]
To you for fixing :wink:
