### ISSUE TITLE
Snippets not working

### ISSUE THREAD

**Issue by idleberg** [Lukasa/language-restructuredtext#19]
When I type snippets (e.g. the default `image` or `link`), they will not be completed. From Sublime Text I'm used that you have to explicitly enable snippets for the text scope, but since HTML snippets work in Atom, I don't suspect that's the case. Any idea why they don't work?

**Comment by Lukasa** [comment]
Ah, sorry, looks like the selector got out of step and so Atom wasn't detecting the snippets properly. I've just released 0.8.0 that should fix that problem. Thanks for the report! :cake:

**Comment by idleberg** [comment]
That was quick, thank you 👍
