### ISSUE TITLE
Syntax Highlighting won't stop in indented blocks

### ISSUE THREAD

**Issue by raphiz** [Lukasa/language-restructuredtext#22]
I stumbled over this issue when I tied to use a code block inside a glossary block.
This compiles just fine with sphinx - but the atom language grammar keeps the syntax highlighting to that language until the next line that begins with no indent.

![012](https://cloud.githubusercontent.com/assets/605630/10304064/10926a64-6c18-11e5-9683-d95b392cbd25.png)

Same issue when just using indented blocks:
```rst

    Indented Block...
    .. code-block:: java

        Point a = new Point();

    Other stuff in indented block...
    
Works fine again...
```

**Comment by Lukasa** [comment]
Hmm, the grammar might not be restrictive enough here. Let me take a look.

**Comment by Lukasa** [comment]
Hmm, a quick reading of the regex seems to suggest that the block should stop marking when dedented back to the level of the `..`.  Let me dig further.

**Comment by Lukasa** [comment]
Ah, no, nevermind, I see it. It looks like that regex could never have matched an indented block. Hmm.

**Comment by Lukasa** [comment]
@raphiz Can you try the code in #23 and confirm it solves your problem (and more importantly, doesn't introduce new ones)?

**Comment by raphiz** [comment]
Yay, thanks for the quick response!
The code from #23 seems to work just fine for the glossary!
However, there is still something going wrong when using just indent blocks...

```rst
Some text....

    Now indent...

    .. code-block:: java

        class Foo {
        }

    Still syntax highlighting here...

But here it's gone!
```
![013](https://cloud.githubusercontent.com/assets/605630/10306593/72b571f4-6c28-11e5-8ce8-da94cacb64e0.png)

I tried out some other test cases - there everything seems to work fine!

**Comment by Lukasa** [comment]
Hmm, weird. I'll try and take another look this afternoon. Regexes make me sad. :disappointed:

**Comment by remexre** [comment]
Is there any progress on this? Working with Lisp means code blocks have unmatched 's and `s, which do interesting things to the syntax highlighting for the rest of the file...

**Comment by Lukasa** [comment]
No progress so far I'm afraid, I'd welcome some investigation!

**Comment by Alhadis** [comment]
[Fixed.](https://github.com/Lukasa/language-restructuredtext/pull/38)
