### ISSUE TITLE
multiline comment [feature request]

### ISSUE THREAD

**Issue by alustig3** [Lukasa/language-restructuredtext#24]
It would nice to have the ability to highlight multiple lines and then press <kbd>alt</kbd> + <kbd>/</kbd> to add a `.. ` at the beginning of each line that is highlighted

**Comment by Lukasa** [comment]
That sounds entirely reasonable, @alustig3. Do you think you'll have the ability to submit a pull request for this?

**Comment by alustig3** [comment]
It turns out snippets are not working right now either. I believe 2bef6ea is the cause of the problem. Going back to  223cc14 fixes both problems so multiline comments and snippets both work as expected.

**Comment by Lukasa** [comment]
Resolved by #26, fix available in 0.10.0. Thanks again @alustig3! :sparkles: :cake: :sparkles:
