### ISSUE TITLE
Link snippet starts with newline, lacks space.

### ISSUE THREAD

**Issue by bilderbuchi** [Lukasa/language-restructuredtext#29]
If I add a link in running text using the snippet, e.g. `My homepage is at lin<Tab>`, there are several issues. First, the snippet starts with a newline, so it autofills to 
```
My homepage is at 
`Title<http://link>`_
```
which does not look like it's desired.

Second, there is no space between `Title` and `<`, which apparently is illegal link markup, so when I fill out the link with `bar<Tab>foo.com`, my Sphinx complains with ` ERROR: Unknown target name: "bar<foo.com>".` :-( Adding a space after `bar` fixes the issue, so this probably should be made part of the snippet?

Third, after filling the Title and URL, I would have expected another `<Tab>` to jump the cursor to after the snippet so that I can continue typing, but this only adds a tab-space after the URL. Am I using this wrong, or is this a bug?

This is with version 0.10.0, on Atom 1.3.0.

**Comment by Lukasa** [comment]
Thanks for the report!

Yeah, both of those are hilariously wrong. I've just pushed 0.11.0 which should fix this. Thanks! :sparkles: :cake: :sparkles:

**Comment by bilderbuchi** [comment]
hah, great! awesome response time, thanks!

**Comment by Lukasa** [comment]
;) My pleasure! You caught me in-between sessions of sitting with my head in my hands weeping softly about flow control and backpressure, so this was light relief in comparison. You have a great day now!

**Comment by bilderbuchi** [comment]
ah, nice. process engineer or something?

**Comment by Lukasa** [comment]
Networks: right now specifically HTTP/2 and Python.

**Comment by bilderbuchi** [comment]
ah ^^. you had me thinking about [these](http://www.bronkhorst.com/en/products/gas_flow_meters_and_controllers/).

**Comment by Lukasa** [comment]
Heh, flow control and back pressure are terms deliberately intended to be analogous to fluid flow.
