### ISSUE TITLE
Incomplete support for section underlines

### ISSUE THREAD

**Issue by brettcannon** [Lukasa/language-restructuredtext#30]
According to http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#sections the complete list is `! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~`. The recommended list is `= - ` : . ' " ~ ^ _ * + #`. Unfortunately the support in the package doesn't fully cover the recommended list, let alone the complete list. It would be great if support for at least the recommended list was added.

**Comment by Lukasa** [comment]
Seems reasonable to me! Want to open a PR with the change @brettcannon?

**Comment by brettcannon** [comment]
PR is untested, but it should add all of the recommended symbols for section underlines.
