### ISSUE TITLE
autocompletion

### ISSUE THREAD

**Issue by fiziko** [Lukasa/language-restructuredtext#35]
Hi,

autocompletion does not work for me, when your package is active.

That is, it does work if I type "le..." for example - but not for anything else...

Any help?

![screenshot](https://cloud.githubusercontent.com/assets/5688765/13347301/2e55362e-dc6d-11e5-859c-a5092ea26f68.png)

**Comment by Lukasa** [comment]
So, does `image<tab>` not work?

**Comment by fiziko** [comment]
Hi, sorry, image<tab> works fine. But I want also completion for unspecific words -- for anything that has already been typed in this buffer before (or in other buffers).

Not only completion of "keywords", but also completion for "anything already appearing anywhere else"...

**Comment by Lukasa** [comment]
Oh I see. It's not clear to me how this package could possibly affect that.

**Comment by fiziko** [comment]
But it does, I think. Because, for me, in other grammars/languages autocompletion works just fine...

Any idea to whom this might be clear of how to find out?

**Comment by Lukasa** [comment]
I think you'd have to get someone who knows Atom very deeply to take a look.

**Comment by fiziko** [comment]
Hi, thanks Lukasa, Maybe you are right. But I guess, it would also have been possible to track down the error. Anyway - just forget about it. Not so important. I will try to find a workaround. Thanks for your help anyway. Regards, Sven

**Comment by Alhadis** [comment]
I'm wondering if this is the culprit:

<img src="https://cloud.githubusercontent.com/assets/2346707/15779021/3be1b516-29dd-11e6-909f-ec75b9942075.png" />

Note the blacklist's default setting: `.source.gfm`. Recall that this package is also using `.source.gfm` (this was brought up in #20).

**Comment by Lukasa** [comment]
Heh, that's entirely possible as a problem.

**Comment by Alhadis** [comment]
I'm in the middle of... uh, reStructuring the entire grammar. Part of the matching problems I'm seeing (particularly with tables and substitution references) are to do with pattern ordering as much as their scope.

I've changed the scope to the original value of `text.restructuredtext`. When this is done, I'll look into having this grammar used to supply syntax highlighting on GitHub, which will address the highlighting issue Luthaf raised in #13.
