### ISSUE TITLE
Escaping mechanism does not work for *, **, |

### ISSUE THREAD

**Issue by wismill** [Lukasa/language-restructuredtext#36]
Hi, according to the [escaping mechanism](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#escaping-mechanism) of reStructuredText, the following text should not be highlighted:

```
These \*symbols\* should be escaped.
These \*\*too\*\*.
What about \|these\|?
```

**Comment by Lukasa** [comment]
Yup, you're absolutely right.

A quick sample paragraph suggests the main problem is with `*` and `|`. Most of the other regexes fail to match if backslashes are present.

**Comment by Lukasa** [comment]
Resolved in v0.13.

**Comment by Lukasa** [comment]
Thanks for the report! :sparkles: :cake: :sparkles:

**Comment by wismill** [comment]
That was fast! Thanks
