### ISSUE TITLE
Not able to set tab length to 2 if main settings are different

### ISSUE THREAD

**Issue by henri-hulski** [Lukasa/language-restructuredtext#37]
In my main settings I have a tab length of 4.
In reStructuredText I want a tab length of 2 which is actually the default.
But when I enter a tab length of 2 or also when I enter nothing it got changed to 4.
Other values are excepted. 
I think this is the case, because 2 is the default value which gets overridden by the main settings.

**Comment by Lukasa** [comment]
I don't think that this package actually sets a tab width anywhere. Are you sure it's this one?

**Comment by henri-hulski** [comment]
Yes. 
Go to settings in main settings set tab length to 4.
Then go to packages -> language-restructuredtext and here you can also set the tab length. If the field is empty there is written default: 2.
When you enter now 2 it changes immediately to 4.
When you make it empty  it also changes to 4.

**Comment by Lukasa** [comment]
Right, but what I'm saying is that there is literally no change to the settings in this module. None. It's left entirely at the defaults. So if your Atom is exhibiting this problem it's surely a problem with Atom, not this module.

**Comment by henri-hulski** [comment]
But I can set it to any other value like 3 or 5.

**Comment by Lukasa** [comment]
To be clear, I'm not disputing that the problem exists. I just don't see how it can possibly be this module. Feel free to look through its code, there isn't much.

**Comment by henri-hulski** [comment]
Yeah it seems to be a bug with the language implementation of atom 1.7.
In language-html I had the same situation but there it worked. I was setting it up in atom 1.6.
Now I changed it and had the same behavior. 
And I'm not able to set it up again. 

So no problem with this module ;-)

**Comment by henri-hulski** [comment]
The same with Atomic 1.8 beta. 
So I think I have to put an issue there.
