### ISSUE TITLE
After updating to 0.16, the syntax highlighting color of sections disappear.

### ISSUE THREAD

**Issue by amoshyc** [Lukasa/language-restructuredtext#42]
The color of the section part used to be green, but changing to white after updating to 0.16.
Is it the intended result?

See the window on the left.
![screenshot from 2016-06-11 00-19-36](https://cloud.githubusercontent.com/assets/3981689/15971024/3c0ca74c-2efd-11e6-812b-22e51901915e.png)

Window on the right is how markdown code was rendered and it is what I'm expecting.

Another screenshot
![screenshot from 2016-06-11 00-29-09](https://cloud.githubusercontent.com/assets/3981689/15971426/9a8e46da-2efe-11e6-8a0f-14271ba4b12c.png)

I'm using
```
language-restructuredtext 0.16.0
Atom 0.18
Fedora 23
```

**Comment by Lukasa** [comment]
Do you have screenshots of the prior rendering?

@Alhadis, you may find this interesting.

**Comment by Alhadis** [comment]
@amoshyc Can you tell us what themes you're using, and what the syntax looked like beforehand?

I'm also not sure what the Markdown file has to do with this... it's a completely different language.

**Comment by amoshyc** [comment]
I'm sorry I don't have screenshots of the prior rendering.
The screenshot of the markdown file in my previous comment demonstrates what I'm expecting and it is the syntax color rst used to be. (Color of the headers is green)

I'm using [`monokai`](https://atom.io/themes/monokai) with ui theme `atom dark`.

**Comment by Alhadis** [comment]
Okay, the "green" parts you're referring to are actually commented-out sections. That's the expected result.

When you say "headers", what are you referring to? The `=================` parts?

**Comment by amoshyc** [comment]
Yes.
```
================
Header
================
```

**Comment by Alhadis** [comment]
Ah, [this is](https://github.com/kevinsawicki/monokai/blob/master/index.less#L48) probably why you were seeing it. Monokai applies Markdown-specific styling, and the theme was previously pretending to be Markdown before v0.16. This was changed for compatibility reasons.

If you feel strongly about borders not having highlighting, you might want to file an issue on the Monokai repository.

**Comment by amoshyc** [comment]
OK. Thank you

**Comment by Lukasa** [comment]
Thanks folks!
