### ISSUE TITLE
Add math markup highlighting

### ISSUE THREAD

**Issue by mangecoeur** [Lukasa/language-restructuredtext#44]
Similar to language-pfm, it would be nice to have math scope + highlighting in `.. math:` blocks and `:math:` inline.

**Comment by Lukasa** [comment]
Agreed! I'll mark this as contributor friendly for someone to pick it up.

**Comment by mangecoeur** [comment]
Incidentally once language-rst marks math blocks I can add preview support for them in my inline-preview plugin: https://atom.io/packages/preview-inline

**Comment by Alhadis** [comment]
Well you nailed this, so... think we can close the book on this issue. =)
