### ISSUE TITLE
syntax highlight issues for unmatched quotes (for apostrophes)

### ISSUE THREAD

**Issue by tardyp** [Lukasa/language-restructuredtext#47]
The following snippet tries to match a closing quote, which it is just an apostrophe. 
I have no problem if I use http://www.fileformat.info/info/unicode/char/2019/index.htm but I would prefer to stick with ASCII as much as possible.

    Twisted's service implementation does not support asynchronous ``startService`` methods.

**Comment by Alhadis** [comment]
Erm, I'm not sure what the issue is here... what are you seeing, exactly?

**Comment by Alhadis** [comment]
@tardyp Can you post some screenshots of what you're seeing? I don't see any error highlights with that text.

**Comment by tardyp** [comment]
Interresting you can't reproduce..
This is for this file:
https://raw.githubusercontent.com/buildbot/buildbot/master/master/docs/developer/utils.rst

I get:
![image](https://cloud.githubusercontent.com/assets/109859/19308836/f01474e6-9081-11e6-859b-59632ac8f67e.png)

**Comment by tardyp** [comment]
and for the other issue:

![image](https://cloud.githubusercontent.com/assets/109859/19308961/8644fa1c-9082-11e6-8f26-f94e95249a93.png)

**Comment by Alhadis** [comment]
Ah-hah, I can see what's wrong now. There's a runaway issue in `.. py:method:: get(key, \*\*miss_fn_kwargs)`.

Fixing.

**Comment by tardyp** [comment]
indeed, those two are related to the same problem (sorry for the noise)

they are triggered by this line

.. py:function:: eventually(cb, *args, \*\*kwargs)

the highlight is fixed when I switch to:

.. py:function:: eventually(cb, *args, **kwargs)

**Comment by tardyp** [comment]
interrestingly, when I fixed the ```\*\*``` in this file, then the last python snippet is not highlighted anymore

**Comment by Alhadis** [comment]
Are you using [MagicPython](https://github.com/MagicStack/MagicPython) by any chance?

**Comment by tardyp** [comment]
> Are you using MagicPython by any chance?

I don't, but it does not change much when I install it

**Comment by Alhadis** [comment]
Alright, I believe I've fixed it. There *is* an error with the document you linked to, but I believe that's because of an incorrect backtick:

    returned from child services` ``sta

The one that's used after `services` is what's confusing the highlighter. There's not much we can do about that without impacting the accuracy of other documents where a leading space is used inside a `link`. Since this is more an authoring issue, I'd prefer to leave that matter as-is.
