### ISSUE TITLE
syntax highlight issues for backslash inside double backquote

### ISSUE THREAD

**Issue by tardyp** [Lukasa/language-restructuredtext#48]
Following snippet is valid sphinx, but produce annoying warning highlights.

    It considers any of ``\r``, ``\n``, and ``\r\n`` to be newlines.
    Because of the ambiguity of an append operation ending in the character ``\r`` (it may be a bare ``\r`` or half of ``\r\n``), the last line of such an append operation will be buffered until the next append or flush.

**Comment by Alhadis** [comment]
Can we please keep this confined to [the one issue](https://github.com/Lukasa/language-restructuredtext/issues/47)? The matters might be related, and having two separate issues makes feedback difficult.
