### ISSUE TITLE
Please add support for a few more Sphinx extensions

### ISSUE THREAD

**Issue by sitsofe** [Lukasa/language-restructuredtext#49]
(I was directed over here because Github uses TextMate-style language grammars through the linguist project (https://github.com/github/linguist/ ) and linguist points (https://github.com/github/linguist/tree/master/vendor/grammars ) to the language-restructuredtext project)

Could support for a few more Sphinx extensions be added? Over on https://gist.github.com/sitsofe/5610dafcddc5c89c8dbb9e5d3bce668d#job-description the one that is most problematic is the `.. option::` directive (http://www.sphinx-doc.org/en/stable/domains.html?highlight=option#directive-option ). There are few others such as the `:option:` inline markup (http://www.sphinx-doc.org/en/stable/markup/inline.html#role-option ) and `:manpage:` inline markup (http://www.sphinx-doc.org/en/stable/markup/inline.html?highlight=manpage#role-manpage ) but those are more minor...

**Comment by Alhadis** [comment]
It'd be my pleasure. Give me a comprehensive list of what you'd like added and I'll see to it right away.

Doesn't matter if they're minor, it's good to be comprehensive.

**Comment by sitsofe** [comment]
Wow - thank you!

My own selfish reasons are to have enough to render https://github.com/axboe/fio/blob/master/HOWTO and https://github.com/axboe/fio/blob/master/README on github.

For directives that would be:
```
.. option
```

For inline markup:
```
:command:
:file:
:kbd:
:manpage:
:noindex:
:option:
:ref:
```

If you're looking for the full list beyond what I need I guess it would be http://www.sphinx-doc.org/en/stable/domains.html?highlight=option#the-standard-domain and http://www.sphinx-doc.org/en/stable/markup/inline.html?highlight=manpage#inline-markup .

I didn't mean it as a demand so let me know what you think.

**Comment by Alhadis** [comment]
No problem. I'll start soon.

**Comment by Alhadis** [comment]
\* <code>s/soon/once I've finished pillaging VSCode for stuff that's missing from [file-Icons](https://github.com/file-icons/atom)/i;</code>

Common typo, sorry.

**Comment by Alhadis** [comment]
Wait. Are you expecting this to affect the **rendered** markup on GitHub, or just reStructuredText's syntax highlighting? It occurred to me just now you mightn't know that the two are very separate. We can control syntax highlighting, but the way GitHub renders markup is entirely up to them.

If it's the latter, you'd be better off submitting a request to GitHub support.

**Comment by Alhadis** [comment]
Okay, yeah, after examining this closer, I realise this is what you probably meant - the highlighting for `.. option` directives looks fine in Atom, as do the other tags you mentioned.

Feel pretty silly now, heh.

**Comment by sitsofe** [comment]
@Alhadis You're absolutely right - looks like I went in the wrong direction. Investigating further the raw markup to HTML conversion is done by https://github.com/github/markup using rst2html . The problem is rst2html errors on Sphinx extensions which is why the Sphinx project recommends using a `.txt` extension rather `.rst` (http://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html#filenames ).
