### ISSUE TITLE
Section snippets don't work as expected

### ISSUE THREAD

**Issue by AusIV** [Lukasa/language-restructuredtext#5]
When I use the section snippets, I type `sec`, hit tab and then see:

    subsection name
    ${1/(.)|\s/(?1:=:=)/g}

If I continue typing, it replaces "subsection name" with what I type as expected, but the second line just looks like a regular expression.

**Comment by e2jk** [comment]
I was trying to figure out how to have this regex "executed" to create the appropriate underline, looking for documentation on how this should work. But looking at this bug report, I understand this is not supposed to work ;)

I would suggest replacing these regexes by fixed-sized underlines for now, and later investigate if there is a mechanism to dynamically adjust the length. This would prevent confusion with new users like me, and is still better than the current situation as the snippets are actually making you do more work than if they didn't exist ;)

* with the snippet:
  - enter the snippet's prefix, `tab`
  - enter the section's name
  - delete the regex, `enter`
  - add the appropriate number of delimiters
* without the snippet:
  - enter the section's name, `enter`
  - add the appropriate number of delimiters
