### ISSUE TITLE
Highlighting breaks when inline code directive content ends in a colon

### ISSUE THREAD

**Issue by stadelmanma** [Lukasa/language-restructuredtext#52]
This issue pops up when ever an in-line code directive is used that ends in a colon without a space. 
The following cause issue:
    
    :code:`:`
    :code:`foobar:`

![image](https://cloud.githubusercontent.com/assets/16710141/24702291/1d96a06e-19cc-11e7-88cb-c52fe409e50f.png)

But this does not:
    
    :code:`:foobar`
    :code:`foo: bar`
    :code:`foo bar:`

![image](https://cloud.githubusercontent.com/assets/16710141/24702309/2f20111c-19cc-11e7-9544-aefb1ec02a55.png)

**Comment by Alhadis** [comment]
What's the expected behaviour for reStructuredText?

I've become rusty in my knowledge of the language, lately... sorry... :(

**Comment by stadelmanma** [comment]
I believe it is should still behave like a regular inline literal. 

Although, I must confess I didn't know about the double backtick literals until about an hour ago when I was picking through the grammar, which are a much better fit for my use case. Granted might still be worth a fix.

**Comment by Alhadis** [comment]
It's queued on my todo list.

**Comment by Alhadis** [comment]
@stadelmanma Do you mind if I include portions of [the `.rst` file you were editing](https://raw.githubusercontent.com/stadelmanma/netl-AP_MAP_FLOW/master/examples/running-the-flow-model.rst) as a spec-fixture for this package? Just to help guard against regressions...

**Comment by stadelmanma** [comment]
You are more than welcome to use all the bits and pieces you need. I am currently revising my README's and examples so you might need to go back to an older commit depending on what all I change as I rework them.

**Comment by Alhadis** [comment]
Ah, thank you! :) Wanted to make sure there weren't any licensing restrictions attached to my copy+pasta, heh.

I generally prefer to test using real-world examples whenever possible.

**Comment by Alhadis** [comment]
Fun fact: writing grammar specs is a serious pain-in-the-arse.

It goes into overdrive when you spend half the day thinking you've concocted a clever shortcut, only to spend the other half failing to get it working. It's now 1:30 am and I'm wondering where the hell my last 24 hours went.

... fuck the specs, I'm just gonna fix these bugs and cut a release. Christ... :(

**Comment by Alhadis** [comment]
I was worried this would take hours, but literally the first thing I tried fixed it.

<img src="https://cloud.githubusercontent.com/assets/2346707/24763689/76046b40-1b35-11e7-9a88-e34002bb3f62.png" width="353" alt="Figure 1" /> <img src="https://cloud.githubusercontent.com/assets/2346707/24763712/8758277e-1b35-11e7-91d3-d2e5beeb29c0.png" width="400" alt="Figure 2" />

And it was a 1-character fix.
