### ISSUE TITLE
Live update flashing

### ISSUE THREAD

**Issue by pkqxdd** [Lukasa/language-restructuredtext#53]
When I enabled live update, whenever I changed the source file, the preview panel flashes with a github symbol and "loading rst", which becomes very distractive and I had to disable the live update mode. Are there any ways to disable the loading icon or bind a keystroke to update preview? (All I can find is `rst preview: toggle`, I want something like `rst preview: update`)

**Comment by Alhadis** [comment]
I think you're filing an issue to the wrong repository, dude, because I have no idea what you're talking about.
