### ISSUE TITLE
Styling for default Atom themes

### ISSUE THREAD

**Issue by gamesbook** [Lukasa/language-restructuredtext#54]
issue #9 refers.

I am very new to Atom, but a regular rst user.  I'd appreciate if there were some way to have the same type of elements "coded" in some way across all the default Atom themes.  

In particular, when you compare the normal light theme vs solarized light (which I use because its not as harsh in contrast as most of the others), you can see that styling is not the same between them; code in backticks is not styled nor is code text in indented blocks.

I am not sure how or where to begin to make any changes to make this work?

![light](https://user-images.githubusercontent.com/354027/26977011-9bb1c19e-4d26-11e7-983e-60a411c198ec.png)

![solarized-light](https://user-images.githubusercontent.com/354027/26977022-a23d0802-4d26-11e7-91d6-4d1b3b1689e7.png)

**Comment by Lukasa** [comment]
My understanding is that this has much more to do with the Atom theme than with the language parser: the language parses identically in all cases, the two themes have chosen to highlight differently.

**Comment by Alhadis** [comment]
👋 Hey mate,

Well, that has nothing to do with this package. What you've described are styling differences between different *syntax themes*. **Syntax themes** are distinct from **UI themes** in they only change the colours and formatting of the text editor's contents.

You can [read more on this subject here](http://flight-manual.atom.io/hacking-atom/sections/creating-a-theme/).

**Comment by Alhadis** [comment]
Anyway, a common cause for this issue isn't just theme styling, but a language-grammar not assigning correct scope-names to matched regions of code. [The issue](https://github.com/Lukasa/language-restructuredtext/issues/9) you linked to above is probably a good example.

[I pimped the everloving hell](https://github.com/Lukasa/language-restructuredtext/pull/41) out of this package last year, though. Since then, cross-theme styling has improved *heaps*. However, if there's something I missed that should be catered to, please let me know.

**Comment by gamesbook** [comment]
@Lukasa Again apologies - are you saying this needs to be patched at a theme level (a whole different area)?  In which case, I assume I need to look at the projects that created those themes are figure out how/where/why they differ?

**Comment by Lukasa** [comment]
My assumption is that this is a theming problem. However, as @Alhadis notes, it is *possible* that we have failed to give scopes appropriate names. I don't think this is likely, but it is possible.

**Comment by gamesbook** [comment]
@Lukasa OK, thanks. I was hoping this might be a relatively simple fix, but I have the sense that dealing with theme changes may be above my pay grade.

**Comment by Alhadis** [comment]
@gamesbook You should consider that this is a designer issue, not an oversight on a syntax-theme author's behalf. =)

Please don't forget that your user stylesheet takes precedence over all else here. If you don't like something, chance it the way you like.

You can quickly find which bits to change by opening the developer tools, and using "Inspect Element" to inspect the properties of the offending/bland parts of your code. Easy matter of styling from there. =)

**Comment by gamesbook** [comment]
@Alhadis Its not really a case of "I don't like something" - its more a case of an inconsistency that should not really be there.  Fixing it just for me is not helpful.

**Comment by Alhadis** [comment]
I'm afraid I'm failing to see the issue then. Different elements are inevitably going to be formatted differently by different designers, and even between two different languages by the same designer.

The scopes we're using are valid, but not all of them are known by designers, either. We're using `markup.raw` as the scope-name of backticked code, but "raw markup" isn't something which too many themes widely support.
