### ISSUE TITLE
Add more snippets

### ISSUE THREAD

**Issue by lgarcin** [Lukasa/language-restructuredtext#58]
Would it be possible to add support for more snippets ? For example, it would be nice to have snippet autocompletion for directives and roles described in this [cheatsheet](http://docutils.sourceforge.net/docs/user/rst/cheatsheet.txt).

**Comment by Alhadis** [comment]
We'd be welcome to a PR, mate. 👍

I'd do it myself, but things here have been quite hectic lately. 😢

**Comment by lgarcin** [comment]
Ok I'll give it a try.

**Comment by mshenfield** [comment]
@lgarcin Any specific ones you had in mind? I'd enjoy giving one or two a shot.

**Comment by lgarcin** [comment]
@mshenfield I've  just submitted a pull request #59

**Comment by Alhadis** [comment]
#59 was merged ages ago, so closing this.
