### ISSUE TITLE
Highlight markups with line breaks

### ISSUE THREAD

**Issue by vmassuchetto** [Lukasa/language-restructuredtext#61]
Highlighting won't continue when there's a line break. See:

![captura de tela de 2017-12-30 01-49-53](https://user-images.githubusercontent.com/814115/34451133-d3d2ce24-ed03-11e7-96d9-0617b0f0b447.png)

As they produce the same output, I guess they should be marked the same on the editor.

![captura de tela de 2017-12-30 01-50-10](https://user-images.githubusercontent.com/814115/34451135-d8705942-ed03-11e7-94a8-95b418b58107.png)

**Comment by Alhadis** [comment]
Fixed.

<img src="https://i.imgur.com/c4jt321.png" alt="This is fine" />
