### ISSUE TITLE
Spell checking 

### ISSUE THREAD

**Issue by cbarrick** [Lukasa/language-restructuredtext#64]
Markdown documents have spell checking enabled by default. It would be great if rst documents were given the same treatment.

For now, my workaround is to switch the grammar to markdown periodically.

**Comment by Alhadis** [comment]
> For now, my workaround is to switch the grammar to markdown periodically.

There's a setting that controls which languages are spell-checked. Open the `spell-check` package's settings and add `text.restructuredtext` to the **Grammars** setting:

<img src="https://user-images.githubusercontent.com/2346707/38776039-a380f5a6-40d3-11e8-98c4-d8af2bf5ccb1.png" width="729" alt="Figure 1" />
