### ISSUE TITLE
Dynamic-size underline for section snippets

### ISSUE THREAD

**Issue by e2jk** [Lukasa/language-restructuredtext#7]
Follow up on #5:

Commit 7897d5b7983e862185179e739fe9e838db5a79ac replaced the non-working regexes with fixed-size underline, rendering these snippets more useful in the short term. However, ideally we would like to have the underlines be generated dynamically: the number of underline characters should be the same as the section name's length.

That would likely require a post-snippet-editing mechanism be added to the snippet package?

**Comment by Alhadis** [comment]
I added a command to resize underlines to fit their section names. Open the command palette and search for `Language Restructuredtext: Fit Borders`. That'll update the border that's currently under the cursor.
