### ISSUE TITLE
linter-rst: unexpected error

### ISSUE THREAD

**Issue by dreamalligator** [Lukasa/language-restructuredtext#70]
Hi! It appears as if the tree parsing works fine for the Atom plugin, but we are getting the following warning. I assume this just means that this dependency needs to be included in this project.

![warning](https://user-images.githubusercontent.com/2218331/119699803-63012500-be07-11eb-9feb-5ada968bf633.png)

https://github.com/albertvisser/Rst2HTML/

**Comment by Alhadis** [comment]
👋 Hey mate,

Sorry for the slow response. This package only provides syntax highlighting and snippets for reStructuredText, I'm afraid. From the looks of it, this issue should've been submitted to the [`linter-rst`](https://github.com/AtomLinter/linter-rst) package instead.

Hope that helps! Gonna close this, as there's really nothing we can do on our end.
