### ISSUE TITLE
Doesn't handle tags with periods in them

### ISSUE THREAD

**Issue by alex** [Lukasa/language-restructuredtext#8]
This was fixed upstream in: https://github.com/textmate/restructuredtext.tmbundle/commit/608d8bcdea179d4bf3def6244e0d9cf7705f2fea

Not sure how you want to handle porting that commit in.

**Comment by alex** [comment]
It looks like it should be straightforward to make the same change at https://github.com/Lukasa/language-restructuredtext/blob/master/grammars%2Frestructuredtext.cson#L612, but I'm not sure if there's some special procedure for including changes made upstream.

**Comment by Lukasa** [comment]
Thanks @alex, I'll chase this when I get back from work tonight.

**Comment by Lukasa** [comment]
Resolved. =) 0.3.0 is out and should contain this fix.

**Comment by alex** [comment]
<3 thanks.

On Tue, Mar 3, 2015 at 12:29 PM, Cory Benfield <notifications@github.com>
wrote:

> Closed #8 <https://github.com/Lukasa/language-restructuredtext/issues/8>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Lukasa/language-restructuredtext/issues/8#event-245504603>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084
