### ISSUE TITLE
Would you attach a screenshot of how does it look like?

### ISSUE THREAD

**Issue by hbrls** [Lukasa/language-restructuredtext#9]
I'm from Sublime and I'm looking for some equivalent highlighter of this:

![sblime](https://cloud.githubusercontent.com/assets/1220476/6885514/518af2c4-d655-11e4-8eba-443d69beb775.png)

But when I open the same file in Atom, I got this:

![atom](https://cloud.githubusercontent.com/assets/1220476/6885519/aa2dc79e-d655-11e4-989a-a02f89934ec5.png)
 
I'm not sure if I did something wrong. Would you please attach a screenshot of the standard expected behavior? Thanks.

**Comment by Lukasa** [comment]
With Atom, the effectiveness of the highlighting depends on the theme you're using. Basically the language parsing plugin attaches certain names to blocks, which the theme can then choose to highlight or not. Try switching through various themes on your machine and see how they affect the appearance.

I agree that the reStructuredText package is not ideal at this: right now it was basically converted directly from TextMate with no additional work. If you can find some good names to give things to get your theme to highlight more appropriately go for it.

**Comment by hbrls** [comment]
After switching between themes and the dev view, I think I know the conventions behind. Though I might not be able to say it with the Atom terms.

What's your suggestion then? To modify the class names in this repo? Or to create some additional css to my desired theme following the current class names?

**Comment by Lukasa** [comment]
Either would work, but I'll happily merge pull requests that improve the way the theming looks in most of the Atom themes (particularly the defaults).

**Comment by hbrls** [comment]
OK. I will take a look at the official [Markdown](https://github.com/atom/language-gfm) first and make a decision. It looks good with my themes at hand.

**Comment by hbrls** [comment]
#10
